### ISSUE TITLE
Alternative frontend

### ISSUE THREAD

**Issue by krmax44** [k-nut/unisport-frontend#66]
Hi! The site has been really helpful to me, but I wanted some more features. Therefore, I created a new frontend focused on the map. Feel free to take a look: https://github.com/krmax44/unisport-frontend

Thanks a lot for creating this project!

**Comment by k-nut** [comment]
Thanks for letting me know. In a funny coincidence I just did essentially the opposite and replaced the version that is running on unisport.berlin from the old angular implementation to one that uses deno's fresh to render server side. The behaviour should be exactly as it was before though to users and the API also remains (at least for now. I was thinking about decommissioning it eventually but since you are using it, I might as well leave it as is).

I'll close this issue for now since I guess that here is nothing to be changed in this repo but do feel free to let me know if you notice that I could add anything to the API that might be helpful for your version :)
